spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:host.docker.internal:29092}

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: mail-service
    server: ${API_GATEWAY:http://localhost:4953}/mail
    title: Mail service
    version: 1.0.0