spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes: # điều hướng request đến service tương ứng thông qua chỉ định trên url
        - id: authentication-service
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/auth/**, /v3/api-docs/authentication-service
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment} # thay thế ký tự /auth/ thành /
            - ApiRequestFilter
        - id: account-service
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/account/**, /v3/api-docs/account-service
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment} # thay thế ký tự /account/ thành /
            - ApiRequestFilter
        - id: product-service
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/product/**, /v3/api-docs/product-service
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment} # thay thế ký tự /product/ thành /
            - ApiRequestFilter
        - id: order-service
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/order/**, /v3/api-docs/order-service
          filters:
            - RewritePath=/order/(?<segment>.*), /order/$\{segment} # thay thế ký tự /order/ thành /
        - id: inventory-service
          uri: http://host.docker.internal:8086
          predicates:
            - Path=/inventory/**, /v3/api-docs/inventory-service
          filters:
            - RewritePath=/inventory/(?<segment>.*), /inventory/$\{segment} # thay thế ký tự /inventory/ thành /
        - id: mail-service
          uri: http://host.docker.internal:8087
          predicates:
            - Path=/mail/**, /v3/api-docs/mail-service
          filters:
            - RewritePath=/mail/(?<segment>.*), /mail/$\{segment} # thay thế ký tự /mail/ thành /
            - ApiRequestFilter
        - id: orchestrator-service
          uri: http://host.docker.internal:8090
          predicates:
            - Path=/mail/**, /v3/api-docs/orchestrator-service
          filters:
            - RewritePath=/orchestrator/(?<segment>.*), /mail/$\{segment} # thay thế ký tự /mail/ thành /
            - ApiRequestFilter

      springdoc:
        api-docs:
          enabled: true
        swagger-ui:
          enabled: true
          path: /swagger-ui.html
          config-url: /v3/api-docs/swagger-config
          urls:
            - url: /v3/api-docs
              name: API Gateway
            - url: /v3/api-docs/authentication-service
              name: Authentication Service
            - url: /v3/api-docs/account-service
              name: Account Service
            - url: /v3/api-docs/product-service
              name: Product Service
            - url: /v3/api-docs/order-service
              name: Order Service
            - url: /v3/api-docs/inventory-service
              name: Inventory Service
            - url: /v3/api-docs/mail-service
              name: Mail Service

redis:
  host: ${REDIS_HOST:host.docker.internal}
  port: ${REDIS_PORT:6379}

grpc:
  client:
    verify-token-service:
      address: static://${AUTH_GRPC_SERVER:host.docker.internal:9091}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
