spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:quoctay}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:host.docker.internal:29092}
    order-call-back-topic: checkout-order-call-back-topic

stripe:
  apiKey: ${STRIPE_APIKEY:sk_test_51Q91kxRwAzcfsrwCTe0g6ZRkGAP61YAO5vg0UtrLHFiuqrkIf4YBEq2Smu232hQQ0pvd7Iooikzt5z4CjLxUU2uq00NuDmFjuW}

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: payment-service
    server: ${API_GATEWAY:http://localhost:${server.port}}
    title: Payment service
    version: 1.0.0