spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:host.docker.internal:29092}
    updateInventoryTopic: update-inventory-topic
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:quoctay}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: inventory-service
    server: ${API_GATEWAY:http://localhost:${server.port}}
    title: Inventory service
    version: 1.0.0