spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: orchestrator-service
    server: http://localhost:${server.port}
    title: Orchestrator service
    version: 1.0.0