server:
  port: 8089
spring:
  application:
    name: batch-job
  profiles:
    active: @spring.profiles.active@

management: # Health check
  endpoints:
    web:
      exposure:
        include: '*'
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  health:
#    livenessState:
#      enabled: true
#    readinessState:
#      enabled: true
#  prometheus:
#    metrics:
#      export:
#        step: 5s
#        enabled: true

logging:
  level:
    root: INFO
    web: OFF
