
-- Tạo user quoctay với quyền admin
CREATE ROLE quoctay WITH LOGIN SUPERUSER PASSWORD 'password';
-- DROP SCHEMA public;
-- DROP SCHEMA public;
-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION postgres;

-- DROP TYPE public.appointmentstatus;

CREATE TYPE public.appointmentstatus AS ENUM (
	'CANCELLED',
	'COMPLETED',
	'CONFIRMED',
	'PENDING');

-- DROP TYPE public.periodenum;

CREATE TYPE public.periodenum AS ENUM (
	'AFTERNOON',
	'LUNCH',
	'MORNING');

-- DROP SEQUENCE public.appointments_id_seq;

CREATE SEQUENCE public.appointments_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.appointments_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.appointments_id_seq TO quoctay;

-- DROP SEQUENCE public.doctor_schedule_id_seq;

CREATE SEQUENCE public.doctor_schedule_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.doctor_schedule_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.doctor_schedule_id_seq TO quoctay;

-- DROP SEQUENCE public.doctors_id_seq;

CREATE SEQUENCE public.doctors_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.doctors_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.doctors_id_seq TO quoctay;

-- DROP SEQUENCE public.locations_id_seq;

CREATE SEQUENCE public.locations_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.locations_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.locations_id_seq TO quoctay;

-- DROP SEQUENCE public.patients_id_seq;

CREATE SEQUENCE public.patients_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.patients_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.patients_id_seq TO quoctay;

-- DROP SEQUENCE public.specialties_id_seq;

CREATE SEQUENCE public.specialties_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.specialties_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.specialties_id_seq TO quoctay;

-- DROP SEQUENCE public.tbl_product_id_seq;

CREATE SEQUENCE public.tbl_product_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.tbl_product_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.tbl_product_id_seq TO quoctay;

-- DROP SEQUENCE public.time_slots_id_seq;

CREATE SEQUENCE public.time_slots_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.time_slots_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.time_slots_id_seq TO quoctay;
-- public.locations definition

-- Drop table

-- DROP TABLE public.locations;

CREATE TABLE public.locations (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT locations_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.locations OWNER TO quoctay;
GRANT ALL ON TABLE public.locations TO quoctay;


-- public.patients definition

-- Drop table

-- DROP TABLE public.patients;

CREATE TABLE public.patients (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	district varchar(255) NULL,
	province varchar(255) NULL,
	street varchar(255) NULL,
	ward varchar(255) NULL,
	customer_id int8 NOT NULL,
	dob timestamp(6) NULL,
	full_name varchar(255) NULL,
	gender int2 NULL,
	nationality varchar(255) NULL,
	phone varchar(255) NULL,
	CONSTRAINT patients_gender_check CHECK (((gender >= 0) AND (gender <= 1))),
	CONSTRAINT patients_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.patients OWNER TO quoctay;
GRANT ALL ON TABLE public.patients TO quoctay;


-- public.specialties definition

-- Drop table

-- DROP TABLE public.specialties;

CREATE TABLE public.specialties (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	code varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT specialties_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.specialties OWNER TO quoctay;
GRANT ALL ON TABLE public.specialties TO quoctay;


-- public.tbl_product definition

-- Drop table

-- DROP TABLE public.tbl_product;

CREATE TABLE public.tbl_product (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	price float8 NULL,
	updated_at timestamp(6) NULL,
	user_id int4 NULL,
	CONSTRAINT tbl_product_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.tbl_product OWNER TO quoctay;
GRANT ALL ON TABLE public.tbl_product TO quoctay;


-- public.time_slots definition

-- Drop table

-- DROP TABLE public.time_slots;

CREATE TABLE public.time_slots (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"date" date NOT NULL,
	"period" public.periodenum NULL,
	CONSTRAINT time_slots_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.time_slots OWNER TO quoctay;
GRANT ALL ON TABLE public.time_slots TO quoctay;


-- public.doctors definition

-- Drop table

-- DROP TABLE public.doctors;

CREATE TABLE public.doctors (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"name" varchar(255) NULL,
	specialty_id int8 NULL,
	CONSTRAINT doctors_pkey PRIMARY KEY (id),
	CONSTRAINT fkb4ymcpidvwfn4kybv4adfvxcm FOREIGN KEY (specialty_id) REFERENCES public.specialties(id)
);

-- Permissions

ALTER TABLE public.doctors OWNER TO quoctay;
GRANT ALL ON TABLE public.doctors TO quoctay;


-- public.doctor_schedule definition

-- Drop table

-- DROP TABLE public.doctor_schedule;

CREATE TABLE public.doctor_schedule (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	doctor_id int8 NULL,
	time_slot_id int8 NULL,
	CONSTRAINT doctor_schedule_pkey PRIMARY KEY (id),
	CONSTRAINT fkl9tqfnlm9lv0kefn81hpi6y7o FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id),
	CONSTRAINT fkne64fr43e23vvgs63mik1tsjb FOREIGN KEY (doctor_id) REFERENCES public.doctors(id)
);

-- Permissions

ALTER TABLE public.doctor_schedule OWNER TO quoctay;
GRANT ALL ON TABLE public.doctor_schedule TO quoctay;


-- public.appointments definition

-- Drop table

-- DROP TABLE public.appointments;

CREATE TABLE public.appointments (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	note varchar(255) NULL,
	status public.appointmentstatus NULL,
	doctor_schedule_id int8 NULL,
	patient_id int8 NULL,
	CONSTRAINT appointments_pkey PRIMARY KEY (id),
	CONSTRAINT fk6nxveu65xc5g5ykg6eqivf5w FOREIGN KEY (doctor_schedule_id) REFERENCES public.doctor_schedule(id),
	CONSTRAINT fk8exap5wmg8kmb1g1rx3by21yt FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);

-- Permissions

ALTER TABLE public.appointments OWNER TO quoctay;
GRANT ALL ON TABLE public.appointments TO quoctay;




-- Permissions

GRANT ALL ON SCHEMA public TO postgres;
