spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # New database is created when app starts and destroyed when app stops
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: false
    properties:
      hibernate:
        # Format queries
        format_sql: true

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: notification-service
    server: http://localhost:${server.port}
    title: Notification service
    version: 1.0.0

oneSignal:
  apiUrl: ${ONE_SIGNAL_API_URL:https://onesignal.com/api/v1/notifications}
  appId: ${APP_ID}
  apiKey: ${REST_API_KEY}

amazon:
  sns:
    region: ${AMAZON_SNS_REGION:eu-west-1}
    accessKey: ${AMAZON_SNS_ACCESS_KEY}
    secretKey: ${AMAZON_SNS_SECRET_KEY}