spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:quoctay}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: product-service
    server: ${API_GATEWAY:http://localhost:4953}/product
    title: Product service
    version: 1.0.0